CREATE DATABASE IF NOT EXISTS oddle;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  business_type ENUM('INDIVIDUAL', 'COMPANY') NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  country VARCHAR(255) NOT NULL,
  external_id VARCHAR(255),
  subscription_start_date DATE NOT NULL,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('PENDING', 'ACTIVE', 'DELETED', 'SUSPENDED') NOT NULL DEFAULT 'PENDING',
  payout DECIMAL(10, 2) NOT NULL,
  payout_method ENUM('MANUAL', 'AUTO') NOT NULL
);
